apiVersion: v1
kind: Pod
spec:
  containers:
  - name: golang
    image: golang:latest
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  - name: hey
    image:  caladreas/rakyll-hey
    command: ["cat"]
    tty: true
  - name: sonar
    image:  newtmitch/sonar-scanner
    command: ["cat"]
    tty: true